### ISSUE TITLE
Have this bug solved?

### ISSUE THREAD

**Issue by jumpingfrog0** [JenDobson/SKCropNodeBug#1]
Hey, I also found this bug when I wanted to make a scroll view. I search in stackoverflow and google, but I can't find any answer. Did you have any idea to solve this bug?

**Comment by JenDobson** [comment]
I reported the bug, but I never received any notice of action on it from Apple.  If you have a small toy example of the issue, maybe you'll have more luck in reporting it?  I'm not doing any work in iOS these days, so I've let the issue drop for me.

Cheers,
Jen
